version: '3.8'

networks:
  default:
    name: cms_network
    external: true

volumes:
  pgdata:

services:
  server-tcp:
    restart: always
    build: .
    container_name: server-tcp
    ports:
      - "5100:5100"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TCP_SERVER_PORT: ${TCP_SERVER_PORT}
